### ISSUE TITLE
The inData char array is not cleared

### ISSUE THREAD

**Issue by particlewizard** [dyadica/Unity_SerialPort#1]
Issue can be reproduced if you try this:
1) send "A,1" - it is returned exactly as sent.
2) send "A,999" - it is returned exactly as sent.
3) send "A,1" - it is returned as "A,1\n9" !

The inData buffer holds on to previous property data (after the comma) that exceeded more than 1 character, and thus, if the next property data is shorter, leftovers will show up from the previous.

**Comment by dyadica** [comment]
Hi I have now pulled in your fix. Once again thanks
