### ISSUE TITLE
Unity does not receive serial messages on the Mac

### ISSUE THREAD

**Issue by christhian06** [dyadica/Unity_SerialPort#3]
First of all, I would like to thank you very much for the project, which is extremely useful. On Windows the serial communication is good, but on the mac, I was only able to send messages from Unity to the Arduino (Pro Micro), but I can't receive messages on the Unity from Arduino.
Testing the serial communication between the Arduino Pro Micro and the Arduino IDE running on the Mac, the reception and sending of messages is working normally.

**Comment by dyadica** [comment]
Hi thanks for the feedback and sorry for a late reply!

The scripts were developed on and for Windows; so I'm not that surprised that there are a few issues on a Mac. Furthermore to compound the issue from what I can tell .net ports have always been a little flaky on Mac's! I have just done an update that allows access to all the port settings (e.g. Rts, Dtr) and this may help? Unfortunately I have no way of testing this so give me a go and let me know how you get on etc. If you do manage to resolve the problem by other means then I will happily update the codebase to reflect. It would be nice to also have it working cross platform. It would also be interesting to know how/if the threading implementation also works on a Mac.
