### ISSUE TITLE
Any plan to add IL2CPP support?

### ISSUE THREAD

**Issue by tribbloid** [dyadica/Unity_SerialPort#4]
These are the outcome after I compile the project into an App with IL2CPP:

![Screenshot 2024-09-11 141433](https://github.com/user-attachments/assets/fa21371b-7cfc-499e-b312-6a4e4fcd4606)

With support ofhttps://github.com/yasirkula/UnityIngameDebugConsole

I wonder if it could be solved easily?

**Comment by dyadica** [comment]
Hi, in the short term I have no plans for this as I currently have moved on from Unity. I might have a look in the long term if the licencing truly does stabilise again. From a quick google I came across several threads indicating that IL2CPP serial ports are still not supported. For example:

https://discussions.unity.com/t/il2cpp-notsupportedexception-serialport-getportnames/876441

A potential workaround would be to implement your own C++ library to handle serial communications this could then be tied into the existing script.
